
////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 14.7
//  \   \         Application : xaw2verilog
//  /   /         Filename : FALC56_DCM.v
// /___/   /\     Timestamp : 01/02/2019 20:40:44
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -intstyle I:/NZ/Project2018/OTHER/Fatemi/FPGA_PROG/PCI_REV14_FALC56/TOP_ISE/ipcore_dir/FALC56_DCM.xaw -st FALC56_DCM.v
//Design Name: FALC56_DCM
//Device: xc3s400-5pq208
//
// Module FALC56_DCM
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// Period Jitter (unit interval) for block DCM_INST = 0.05 UI
// Period Jitter (Peak-to-Peak) for block DCM_INST = 0.78 ns
`timescale 1ns / 1ps

module FALC56_DCM(FALC56_DCM_CLK_I, 
                  FALC56_DCM_RST_I, 
                  FALC56_DCM_CLKFX_O, 
                  FALC56_DCM_CLKIN_IBUF_O, 
                  FALC56_DCM_CLK0_O, 
                  FALC56_DCM_LOCKED_O);

    input FALC56_DCM_CLK_I;
    input FALC56_DCM_RST_I;
   output FALC56_DCM_CLKFX_O;
   output FALC56_DCM_CLKIN_IBUF_O;
   output FALC56_DCM_CLK0_O;
   output FALC56_DCM_LOCKED_O;
   
   wire CLKFB_IN;
   wire CLKFX_BUF;
   wire CLKIN_IBUFG;
   wire CLK0_BUF;
   wire GND_BIT;
   
   assign GND_BIT = 0;
   assign FALC56_DCM_CLKIN_IBUF_O = CLKIN_IBUFG;
   assign FALC56_DCM_CLK0_O = CLKFB_IN;
   BUFG  CLKFX_BUFG_INST (.I(CLKFX_BUF), 
                         .O(FALC56_DCM_CLKFX_O));
   IBUFG  CLKIN_IBUFG_INST (.I(FALC56_DCM_CLK_I), 
                           .O(CLKIN_IBUFG));
   BUFG  CLK0_BUFG_INST (.I(CLK0_BUF), 
                        .O(CLKFB_IN));
   DCM #( .CLK_FEEDBACK("1X"), .CLKDV_DIVIDE(2.0), .CLKFX_DIVIDE(1), 
         .CLKFX_MULTIPLY(3), .CLKIN_DIVIDE_BY_2("FALSE"), 
         .CLKIN_PERIOD(50.000), .CLKOUT_PHASE_SHIFT("NONE"), 
         .DESKEW_ADJUST("SYSTEM_SYNCHRONOUS"), .DFS_FREQUENCY_MODE("LOW"), 
         .DLL_FREQUENCY_MODE("LOW"), .DUTY_CYCLE_CORRECTION("TRUE"), 
         .FACTORY_JF(16'h8080), .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE") ) 
         DCM_INST (.CLKFB(CLKFB_IN), 
                 .CLKIN(CLKIN_IBUFG), 
                 .DSSEN(GND_BIT), 
                 .PSCLK(GND_BIT), 
                 .PSEN(GND_BIT), 
                 .PSINCDEC(GND_BIT), 
                 .RST(FALC56_DCM_RST_I), 
                 .CLKDV(), 
                 .CLKFX(CLKFX_BUF), 
                 .CLKFX180(), 
                 .CLK0(CLK0_BUF), 
                 .CLK2X(), 
                 .CLK2X180(), 
                 .CLK90(), 
                 .CLK180(), 
                 .CLK270(), 
                 .LOCKED(FALC56_DCM_LOCKED_O), 
                 .PSDONE(), 
                 .STATUS());
endmodule

